# Generated by Django 5.1.6 on 2025-02-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedio', models.CharField(max_length=200, unique=True)),
                ('quantidade', models.CharField(max_length=10)),
                ('controlado', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=400)),
            ],
        ),
    ]
