# Generated by Django 5.1.5 on 2025-02-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_saida', models.DateField()),
                ('cpf', models.CharField(max_length=15)),
                ('sus', models.CharField(max_length=15)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmacia.estoquefarmacia')),
            ],
            options={
                'ordering': ['-data_saida'],
            },
        ),
    ]
