# Generated by Django 5.1.5 on 2025-02-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_saidaestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='responsacel_entrega',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='saidaestoque',
            name='responsavel_recebimento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
