# Generated by Django 5.1.5 on 2025-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0003_saidaestoque_responsacel_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoquefarmacia',
            name='local',
            field=models.CharField(choices=[('jardim3', 'Jardim Neopolis 3')], default='jardim3', max_length=50),
            preserve_default=False,
        ),
    ]
