# Generated by Django 5.1.5 on 2025-02-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0004_estoquefarmacia_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaRemediosRecitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico_da_receita', models.CharField(blank=True, max_length=150, null=True)),
                ('data_receita', models.DateField()),
                ('responsacel_entrega', models.CharField(blank=True, max_length=150, null=True)),
                ('quantidade', models.IntegerField()),
                ('data_saida', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmacia.estoquefarmacia')),
            ],
        ),
    ]
