# Generated by Django 5.1.5 on 2025-04-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0005_saidaremediosrecitas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saidaestoque',
            old_name='responsacel_entrega',
            new_name='responsavel_entrega',
        ),
        migrations.RenameField(
            model_name='saidaremediosrecitas',
            old_name='responsacel_entrega',
            new_name='responsavel_entrega',
        ),
    ]
